# Full mesh flow on the aes-block top design, which has real macros
# (aes_rcon, aes_sbox) placed as dbInst::isBlock() instances.
# This exercises the macro path end-to-end including routing + extraction
# on a non-trivial design.

source "../helpers.tcl"

set orfs /home/wajid/OpenROAD-flow-scripts/flow
set results $orfs/results/asap7/aes-block/base
set plat $orfs/platforms/asap7

# Read the top-level placed ODB (contains aes_rcon + aes_sbox as macros)
read_db $results/3_3_place_gp.odb

# Sub-block macros have their own .lef and .lib generated by ORFS
foreach blk {aes-block_aes_rcon aes-block_aes_sbox} {
    set base $orfs/results/asap7/$blk/base
    set nick [string range $blk 10 end]  ;# strip "aes-block_"
    read_liberty $base/${nick}_typ.lib
}

read_liberty $plat/lib/NLDM/asap7sc7p5t_AO_RVT_TT_nldm_211120.lib.gz
read_liberty $plat/lib/NLDM/asap7sc7p5t_INVBUF_RVT_TT_nldm_220122.lib.gz
read_liberty $plat/lib/NLDM/asap7sc7p5t_OA_RVT_TT_nldm_211120.lib.gz
read_liberty $plat/lib/NLDM/asap7sc7p5t_SIMPLE_RVT_TT_nldm_211120.lib.gz
read_liberty $plat/lib/NLDM/asap7sc7p5t_SEQ_RVT_TT_nldm_220123.lib

read_sdc $results/3_place.sdc

puts "Legalizing initial placement..."
detailed_placement

source $plat/setRC.tcl

# --- Report the real macros this design brings in ---
set block [ord::get_db_block]
set macro_count 0
foreach inst [$block getInsts] {
    if { [$inst isBlock] } {
        set bb [$inst getBBox]
        puts "Macro: [$inst getName]  master=[[$inst getMaster] getName]  bbox=([$bb xMin],[$bb yMin])-([$bb xMax],[$bb yMax])"
        incr macro_count
    }
}
puts "Total real macros: $macro_count"
if { $macro_count == 0 } {
    puts "WARNING: design has no macros — nothing to exercise"
}

# Clock name — aes-block SDC uses 'clk'
set clk_name clk
set buffer_list [list BUFx4_ASAP7_75t_R]

create_clock_mesh \
    -clock $clk_name \
    -h_layer M4 \
    -v_layer M5 \
    -pitch 0.7 \
    -buffers $buffer_list \
    -macro_halo 0.5

puts "Legalizing buffer placement..."
detailed_placement -max_displacement 1000

puts "Setting up proxy BTERMs..."
setup_proxy_bterms -clock $clk_name -proxy_layer M6

puts "Setting up sink BTerms..."
connect_sinks_to_mesh -clock $clk_name -proxy_layer M6

puts "Routing..."
set_routing_layers -signal M2-M7 -clock M2-M7

global_route -guide_file [make_result_file "aes_block_mesh.guide"] \
    -congestion_iterations 50

detailed_route -output_drc [make_result_file "aes_block_mesh_drc.rpt"] \
    -droute_end_iter 1

puts "Connecting proxy BTERMs to mesh..."
connect_proxy_bterms_to_mesh -clock $clk_name

estimate_parasitics -global_routing
capture_mesh_arrivals -clock $clk_name
merge_mesh_nets -clock $clk_name
convert_mesh_swire -clock $clk_name

extract_parasitics -ext_model_file $plat/rcx_patterns.rules \
    -cc_model 10 -coupling_threshold 0.1 -max_res 0 -skip_over_cell

set spice_file [make_result_file "aes_block_mesh.spice"]
set script_dir [file dirname [file normalize [info script]]]
write_mesh_spice -clock $clk_name -output $spice_file -vdd 0.7 \
    -spice_models [list $script_dir/asap7_buf_ideal.spice]

# --- Verify no mesh geometry inside any macro ---
set mesh_net [$block findNet "clk_mesh"]
if { $mesh_net == "NULL" } {
    puts "ERROR: clk_mesh not found"
    exit 1
}

set macro_rects {}
foreach inst [$block getInsts] {
    if { [$inst isBlock] } {
        set bb [$inst getBBox]
        lappend macro_rects [list [$bb xMin] [$bb yMin] [$bb xMax] [$bb yMax] [$inst getName]]
    }
}

set wire_v 0
foreach sw [$mesh_net getSWires] {
    foreach sb [$sw getWires] {
        if { [$sb isVia] } { continue }
        set wx1 [$sb xMin]; set wy1 [$sb yMin]
        set wx2 [$sb xMax]; set wy2 [$sb yMax]
        foreach r $macro_rects {
            lassign $r mx1 my1 mx2 my2 mname
            if { $wx1 < $mx2 && $wx2 > $mx1 && $wy1 < $my2 && $wy2 > $my1 } {
                puts "VIOLATION wire: ($wx1,$wy1)-($wx2,$wy2) overlaps $mname"
                incr wire_v
            }
        }
    }
}

set buf_v 0
foreach inst [$block getInsts] {
    if { ! [string match "mesh_buf_*" [$inst getName]] } { continue }
    set o [$inst getOrigin]
    set bx [lindex $o 0]; set by [lindex $o 1]
    foreach r $macro_rects {
        lassign $r mx1 my1 mx2 my2 mname
        if { $bx >= $mx1 && $bx <= $mx2 && $by >= $my1 && $by <= $my2 } {
            puts "VIOLATION buf: [$inst getName] at ($bx,$by) inside $mname"
            incr buf_v
        }
    }
}

puts ""
puts "===== aes-block mesh verification ====="
puts "Real macros:       [llength $macro_rects]"
puts "Wire violations:   $wire_v"
puts "Buffer violations: $buf_v"
puts "========================================"

set odb_file [make_result_file "aes_block_mesh.odb"]
puts "Writing ODB: $odb_file"
write_db $odb_file

set def_file [make_result_file "aes_block_mesh.def"]
puts "Writing DEF: $def_file"
write_def $def_file

puts ""
puts "View layout with:  openroad -gui $odb_file"

exit [expr {($wire_v == 0 && $buf_v == 0) ? 0 : 1}]
